import { CardConfig, CardConfigLabel } from '@oasisprotocol/rose-app-ui/discover'

export const CARDS_CONFIG: { featured: CardConfig[]; dApps: CardConfig[]; tooling: CardConfig[] } = {
  featured: [
    {
      title: 'Neby',
      type: 'DEX',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://www.neby.exchange/',
    },
    {
      title: 'Accumulated Finance',
      type: 'Liquid staking',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://accumulated.finance/',
    },
    {
      title: 'BitProtocol',
      type: 'CDP Stablecoin',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://bitusd.finance/',
    },
  ],
  dApps: [
    {
      title: 'Thorn',
      type: 'StableSwap',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://thornprotocol.com/',
    },
    {
      title: 'Daosis',
      type: 'Launchpad & Token Minter',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://daosis.io/',
    },
    {
      title: 'Rosy',
      type: 'Meme',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://daosis.io/',
    },
    {
      title: '4P SuperdApp',
      type: 'Web3 Messenger',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://the4thpillar.io/',
    },
    {
      title: "Rakesh's Village",
      type: 'Meme & Token Minter',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://www.rakeshvillage.fun/',
    },
    {
      title: 'Predictoor',
      type: 'Predictions',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://www.predictoor.ai/',
    },
    {
      title: 'Pixelrealm',
      type: 'NFT Marketplace & Gaming Incubator',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://app.pixelrealm.io/',
    },
    {
      title: 'Protocol Monster Labs',
      type: 'Gaming',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://protocolmonsterlabs.com/',
    },
    {
      title: 'Oasis Safe',
      type: 'Multisig Wallet',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://safe.oasis.io/welcome',
    },
    {
      title: 'Midas',
      type: 'RWA Yield',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://midas.app/',
    },
  ],
  tooling: [
    {
      title: 'Empyreal / Simulacrum',
      type: 'SDK & AI Agents',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://empyrealsdk.com/',
    },
    {
      title: 'Router Bridge',
      type: 'Bridge',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://app.routernitro.com/swap',
    },
    {
      title: 'Dexscreener',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://dexscreener.com/oasissapphire',
    },
    {
      title: 'Dappradar',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://dappradar.com/rankings/protocol/oasis-sapphire',
    },
    {
      title: 'DefiLlama',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://defillama.com/chain/Oasis%20Sapphire',
    },
    {
      title: 'Rose wallet',
      type: 'Wallet',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://wallet.oasis.io/',
    },
    {
      title: 'Illuminex',
      type: 'Privacy Wallet',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://illuminex.xyz/',
    },
    {
      title: 'Explorer',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://explorer.oasis.io/',
    },
    {
      title: 'Docs',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://docs.oasis.io/',
    },
    {
      title: 'Transak',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://global.transak.com/',
    },
    {
      title: 'CoinMarketCap',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://coinmarketcap.com/currencies/oasis-network/',
    },
    {
      title: 'CoinGecko',
      imgSrc: 'https://placehold.co/600x400',
      externalLink: 'https://www.coingecko.com/en/coins/oasis',
    },
    {
      title: 'Reclaim Protocol',
      type: 'SDK',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://www.reclaimprotocol.org/',
    },
    {
      title: 'Ra1l',
      type: 'DID',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://ra1l.com/',
    },
    {
      title: 'OWallet',
      type: 'Wallet',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://owallet.io/',
    },
    {
      title: 'Safepal',
      type: 'Wallet',
      imgSrc: 'https://placehold.co/600x400',
      labels: [CardConfigLabel.Grant],
      externalLink: 'https://safepal.com/en/',
    },
  ],
}
